### ISSUE TITLE
Black screen issues

### ISSUE THREAD

**Issue by thoricelli** [ALittlePatate/DevourClient#29]
During a game, after a while my screen will go black, putting on fullbright doesn't work. 
It'll stay black, but moving around will make the screen appear again but only at certain angles.

The UI will also look like this:
![image](https://user-images.githubusercontent.com/29801268/225081048-1c58427c-63e1-471c-9253-d9e62757d77e.png)

https://user-images.githubusercontent.com/29801268/225083434-4381196c-3b19-43b5-b5e7-301d5884d7e6.mp4

**Comment by ALittlePatate** [comment]
We already know about this bug, though we're still unsure why this happens. I might be MelonLoader-related. I'm keeping the issue open.

**Comment by Ostreyn** [comment]
Hello ALittlePatate love ur works , is the issue still not fix?

**Comment by ALittlePatate** [comment]
this got fixed by re-writing the cheat in C++, bypassing MelonLoader

**Comment by FALL1N1** [comment]
It still occurs on latest version (4.2) with MelonLoader 0.7.1

edit: It seems to be logging this in the logs of the game and they are getting large (70-150mb) altho unrelated I think

```
2025-08-15T19:05:50.892Z|0x30a0|d3d11: failed to create 2D texture shader resource view id=1123367 [D3D error was 8007000e]
2025-08-15T19:05:50.892Z|0x30a0|Resource ID out of range in SetResource: 1123367 (max is 1048575)
2025-08-15T19:05:50.892Z|0x30a0|Resource ID out of range in GetResource: 1123367 (max is 1048575)
2025-08-15T19:05:50.892Z|0x30a0|Resource ID out of range in GetResource: 1123367 (max is 1048575)
2025-08-15T19:05:50.892Z|0x30a0|Resource ID out of range in GetResource: 1123367 (max is 1048575)
```
